// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBrkHHZxe_0h3OLbV-EcfJLM40E3E_72Q',
    appId: '1:243453210882:web:065d2d7de0959bef43d21b',
    messagingSenderId: '243453210882',
    projectId: 'sakhi-app-d88d8',
    authDomain: 'sakhi-app-d88d8.firebaseapp.com',
    storageBucket: 'sakhi-app-d88d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAde0HM9l7S-AxRTyh_L8VPRzytMSLyKFY',
    appId: '1:243453210882:android:47442ddcd2f4a17843d21b',
    messagingSenderId: '243453210882',
    projectId: 'sakhi-app-d88d8',
    storageBucket: 'sakhi-app-d88d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsetR5XUyVuZPD6NKZju7OFRhHDMNE3cM',
    appId: '1:243453210882:ios:806e8b43a8bf681943d21b',
    messagingSenderId: '243453210882',
    projectId: 'sakhi-app-d88d8',
    storageBucket: 'sakhi-app-d88d8.firebasestorage.app',
    iosBundleId: 'com.example.sakhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsetR5XUyVuZPD6NKZju7OFRhHDMNE3cM',
    appId: '1:243453210882:ios:806e8b43a8bf681943d21b',
    messagingSenderId: '243453210882',
    projectId: 'sakhi-app-d88d8',
    storageBucket: 'sakhi-app-d88d8.firebasestorage.app',
    iosBundleId: 'com.example.sakhi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBrkHHZxe_0h3OLbV-EcfJLM40E3E_72Q',
    appId: '1:243453210882:web:bac0d7f3cc98eae143d21b',
    messagingSenderId: '243453210882',
    projectId: 'sakhi-app-d88d8',
    authDomain: 'sakhi-app-d88d8.firebaseapp.com',
    storageBucket: 'sakhi-app-d88d8.firebasestorage.app',
  );

}